# Generated by Django 4.1 on 2022-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_field', models.CharField(max_length=64)),
                ('second_field', models.CharField(max_length=64)),
                ('third_field', models.PositiveIntegerField()),
            ],
        ),
    ]
