# Generated by Django 4.1 on 2022-08-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='lastname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='todolists',
            name='third_field',
            field=models.CharField(max_length=64),
        ),
    ]
